apiVersion: v1
kind: Template
labels:
  template: Xray-Event
message: |-
  The following service(s) have been created in your project: xray-event.

         Connection URL: http://xray-event:7001
metadata:
  annotations:
    description: |-
      Xray Event Template

      NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.
    openshift.io/display-name: JFrog Xray Event
    tags: ci-cd,build,repository,jfrog
  name: event
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: event
  spec:
    ports:
    - name: 7001-tcp
      port: 7001
      protocol: TCP
      targetPort: 7001
    selector:
      name: event
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: event
  spec:
    replicas: 1
    selector:
      name: event
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: event
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT}
        initContainers:
        - name: init-xray
          image: ${INIT_CONTAINER_IMAGE}
          command: ['sh', '-c', 'until nc -z -w 2 rabbitmq 5672 && echo rabbitmq ok && nc -z -w 2 mongodb 27017 && echo mongodb ok && nc -z -w 2 postgres 5432 && echo postgres ok ; do sleep 2; done']
          imagePullPolicy: IfNotPresent
        containers:
        - env:
          - name: XRAYCONFIGPATH
            value: /var/opt/jfrog/xray/data
          image: ''
          imagePullPolicy: IfNotPresent
          name: event
          ports:
          - containerPort: 7001
            protocol: TCP
          volumeMounts:
          - mountPath: /var/opt/jfrog/xray/data
            name: volume-xray-event
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
        securityContext:
          supplementalGroups: [1035]
        volumes:
        - name: volume-xray-event
          persistentVolumeClaim:
            claimName: xray-data-pvc
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - event
        from:
          kind: ImageStreamTag
          namespace: ${NAMESPACE}
          name: xray-event:${XRAY_VERSION}

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: XRAY_VERSION
    description: JFrog Xray Version
    displayName: JFrog Xray Version
    value: 1.8.6.5
    required: true
  - name: SERVICE_ACCOUNT
    description: Service account
    displayName: Service account
    required: true
  - name: INIT_CONTAINER_IMAGE
    description: Init container image
    displayName: Init container image
    value: "alpine:3.6"
    required: true
