version: '2'
services:
  postgresql:
    image: postgres:9.5.2
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=password
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
    restart: always
  artifactory-node1:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    container_name: artifactory-node1
    ports:
     - 8081:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    volumes:
     - /data/artifactory/node1:/var/opt/jfrog/artifactory
     - /data/artifactory/ha:/var/opt/jfrog/artifactory-ha
     - /data/artifactory/backup:/var/opt/jfrog/artifactory-backup
    # Mount the postgresql driver. Make sure to have it in your local path (~/postgresql-9.4.1212.jar)
     - ~/postgresql-9.4.1212.jar:/opt/jfrog/artifactory/tomcat/lib/postgresql-9.4.1212.jar
    environment:
     - HA_IS_PRIMARY=true
     - HA_DATA_DIR=/var/opt/jfrog/artifactory-ha
     - HA_BACKUP_DIR=/var/opt/jfrog/artifactory-backup
     - HA_MEMBERSHIP_PORT=10017
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=password
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
  artifactory-node2:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    container_name: artifactory-node2
    ports:
     - 8082:8081
    depends_on:
     - postgresql
     - artifactory-node1
    links:
     - postgresql
    # Must pass this to non primary so it can wait for primary to be up
     - artifactory-node1
    volumes:
     - /data/artifactory/node2:/var/opt/jfrog/artifactory
     - /data/artifactory/ha:/var/opt/jfrog/artifactory-ha
     - /data/artifactory/backup:/var/opt/jfrog/artifactory-backup
    # Mount the postgresql driver. Make sure to have it in your local path (~/postgresql-9.4.1212.jar)
     - ~/postgresql-9.4.1212.jar:/opt/jfrog/artifactory/tomcat/lib/postgresql-9.4.1212.jar
    environment:
     - HA_IS_PRIMARY=false
     - HA_DATA_DIR=/var/opt/jfrog/artifactory-ha
     - HA_BACKUP_DIR=/var/opt/jfrog/artifactory-backup
     - HA_MEMBERSHIP_PORT=10017
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=password
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:latest
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory-node1
     - artifactory-node2
    links:
     - artifactory-node1
     - artifactory-node2
    volumes:
     - /data/nginx/log:/var/log/nginx
     - /data/nginx/conf.d/ha:/etc/nginx/conf.d
    # To use your own certificate, just put your .key and .pem files in /data/nginx/ssl before running
     - /data/nginx/ssl:/etc/nginx/ssl
    environment:
     - ART_BASE_URL=http://artifactory-node1:8081/artifactory
     - SSL=true
    restart: always
