{{- if .Values.serviceInternal.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.name" . }}-internal
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.nginx.name }}-internal"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.serviceInternal.annotations }}
  annotations:
{{ toYaml .Values.serviceInternal.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: {{ .Values.nginx.externalPortHttp }}
    targetPort: {{ .Values.nginx.internalPortHttp }}
    protocol: TCP
    name: {{ .Values.nginx.name }}http
  - port: {{ .Values.nginx.externalPortHttps }}
    targetPort: {{ .Values.nginx.internalPortHttps }}
    protocol: TCP
    name: {{ .Release.Name }}https
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.nginx.name }}"
    release: {{ .Release.Name }}
{{- end }}
