kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvmysql1
  labels:
    type: mysql-local
    group: artifactory-k8s-demo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
      matchLabels:
        type: "mysql-local"