kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvnginx1
  labels:
    type: nginx-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginx"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        type: "nginx-local"