kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvpostgresql1
  labels:
    type: postgresql-local
    group: artifactory-k8s-demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
      matchLabels:
        type: "postgresql-local"